memorelaine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('w@k3b@ck3ndp0rt@l/', admin.site.urls),

    # MEMORYWALL APP URLS
    path('', include('memorywall.urls')),

    # ACCOUNTS APP URLS
    path('profile/', include('profile.urls')),
]

memorywall/urls.py
# urls.py -> memorywall
from django.urls import path
from . import views

app_name = 'memorywall'

urlpatterns = [
    path('', views.home, name='home'),
]

profile/urls.py
# urls.py -> accounts
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/', views.detail, name='detail'),

    # AUTH
    path('signup/', views.create_user, name='create_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

profile/models.py
# models.py -> account
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address1 = models.CharField(max_length=100, blank=True)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zip_code = models.IntegerField(blank=True)
    country = models.CharField(max_length=2, blank=True)
    phone = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return f'{self.user.last_name}, {self.user.first_name}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

profile/forms.py
# forms.py -> account
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('address1', 'address2', 'city', 'state', 'zip_code', 'country', 'phone')

memorywall/views.py
# views.py -> memorywall
from django.shortcuts import render

def home(request):
    return render(request, 'memorywall/home.html')

profile/views.py
# views.py -> account
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import ProfileForm, UserForm
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'profile/home.html')

@login_required
def detail(request):
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile/detail.html', {'user_form': user_form, 'profile_form': profile_form})


def create_user(request):
    if request.method == 'GET':
        return render(request, 'profile/create_user.html', {'user_form': UserForm()})
    else:
        if request.POST['password'] == request.POST['password_check']:
            try:
                new_user = User.objects.create_user(
                    username=request.POST['username'],
                    first_name=request.POST['first_name'],
                    last_name=request.POST['last_name'],
                    email=request.POST['email'], 
                    password=request.POST['password'])
                new_user.save()
                login(request, new_user)
                return redirect('profile:detail')
            except IntegrityError:
                return render(request, 'profile/create_user.html', {'user_form': UserForm(), 'error': 'Username already in use. Please choose a different username.'})
        else:
            print("hello")
            return render(request, 'profile/create_user.html', {'user_form': UserForm(), 'error': 'Passwords did not match.'})

def create_profile(request):
    if request.method == 'GET':
        return render(request, 'profile/create_profile.html', {'profile_form': ProfileForm()})
    else:
        form = ProfileForm(request.POST)
        new_profile = form.save(commit=False)
        new_profile.owner = request.user
        new_profile.save()
        return redirect('memorywall:home')


def login_user(request):
    if request.method == 'GET':
        return render(request, 'profile/login_user.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'profile/login_user.html', {'form': AuthenticationForm(), 'error': 'Username or password is invalid.'})
        else:
            login(request, user)
            return redirect('profile:home')


@login_required
def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('profile:home')

memorywall/templates/memorywall/home.html
<h1>Memory Wall</h1>

profile/templates/profile/base.html
<!-- shared: base.html -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'account/site.css' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="{% url 'memorywall:home' %}">
        <img src="{% static 'account/Logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="MemorElaine Logo">
        <span>MemorElaine</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav ml-auto">
          <!-- <li class="nav-item">
            <a role="button" class="btn btn-warning m-1" href="{% static "portfolio/Michael_Wakeland_Resume.pdf" %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a role="button" class="btn btn-info m-1" href="https://www.linkedin.com/in/mike-wakeland-bb844178" target="_blank">LinkedIn</a>
          </li> -->
        </ul>
      </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

profile/templates/profile/create_profile.html
{% extends "profile/base.html" %}
{% load static %}

{% block title %}MemorElaine | Signup{% endblock %}

{% block content %}
<div class="container mt-3">
    <form method="post">
        {% csrf_token %}
        {{ profile_form.as_p }}
        <button class="btn btn-primary" type="submit">Finish</button>
    </form>
</div>
    
{% endblock %}

profile/templates/profile/create_user.html
{% extends "profile/base.html" %}
{% load static %}

{% block title %}MemorElaine | Signup{% endblock %}

{% block content %}
<div class="container mt-3">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <p>
            <label for="password_check">Confirm Password</label>
            <input type="password" name="password_check" id="password_check">
        </p>
        
        <button class="btn btn-primary" type="submit">Next</button>
    </form>
</div>
    
{% endblock %}

profile/templates/profile/detail.html
{% extends "account/base.html" %}
{% load static %}

{% block title %}MemorElaine | My Account{% endblock %}

{% block content %}
<div class="container">
    <h1>My Profile</h1>
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
</div>
    
{% endblock %}

profile/templates/profile/home.html
{% if user.is_authenticated %}
<form method="POST" action="{% url 'profile:logout_user' %}">
    {% csrf_token %}
    <button id="signOutBtn" type="submit">Logout</button>
</form>
{% endif %}
<h1>Account</h1>

profile/templates/profile/login_user.html
{% extends "profile/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'profile:create_user' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}

shared/templates/shared/base.html
<!-- shared: base.html -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shared/site.css' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="{% url 'memorywall:home' %}">
        <img src="{% static 'shared/Logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="MemorElaine Logo">
        <span>MemorElaine</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav ml-auto">
          <!-- <li class="nav-item">
            <a role="button" class="btn btn-warning m-1" href="{% static "portfolio/Michael_Wakeland_Resume.pdf" %}" target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a role="button" class="btn btn-info m-1" href="https://www.linkedin.com/in/mike-wakeland-bb844178" target="_blank">LinkedIn</a>
          </li> -->
        </ul>
      </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>